[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/forge'
cache_path  = 'cache_forge'

remappings = [
  "@oz/=lib/openzeppelin-contracts/contracts/",
  "@std=lib/forge-std/src/"
]
