[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/forge'
cache_path  = 'cache_forge'

remappings = [
  "@oz/=node_modules/@openzeppelin/contracts/",
  "@std=lib/forge-std/src/",
  "@chainlink/contracts/=node_modules/@chainlink/contracts",
  "@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip"
]
