/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockAxelarGasService } from "./MockAxelarGasService";
export type { MockAxelarGateway } from "./MockAxelarGateway";
export type { USDC } from "./USDC";
